[build]
  publish = "build"
  command = "npm run build"

[[redirects]]
from = "/login"
to = "/index.html"
status = 200


[[redirects]]
from = "/home"
to = "/index.html"
status = 200

[[redirects]]
from = "/https://tweeter-backend-production.up.railway.app/tweeter/api/*"
to = "https://tweeter-backend-production.up.railway.app/tweeter/api/:splat"
status = 200