[build]
  publish = "build"
  command = "npm run build"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/*/tweeter/api/*"
to = "https://tweeter-backend-production.up.railway.app/tweeter/api/:splat"
status = 200